name: Maven CI/CD
on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:

   build_and_test:

      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v2

      - name: Set up JDK 17

        uses: actions/setup-java@v1

        with:

           java-version: 17

      - name: Build project with Maven
        run: cd Project && mvn -B package 
  
      - name: Run tests
        run: cd Project && mvn test
